add ability to create new sessions & some fixes
- ls when tmux is not running
- ls and pick when there are spaces in the names

diff --git a/tx b/tx
--- a/tx
+++ b/tx
@@ -57,11 +57,13 @@ list() {
         echo -n "$output"
     }
 
-    local sessions=$(get_tmux_sessions)
+    local sessions=$(get_tmux_sessions "#{session_name}")
 
-    while IFS= read -r session; do
-      session_set["$session"]=1
-    done <<< "$sessions"
+    if [ -n "$sessions" ]; then
+        while IFS= read -r session; do
+          session_set["$session"]=1
+        done <<< "$sessions"
+    fi
 
     local layouts=$(remove_duplicates "$(get_layouts)")
     local fragments=""
@@ -86,7 +88,7 @@ list() {
         } | awk '{print length}' | sort -nr | head -1
     )
 
-    tmux ls -F "#{session_attached}:#{session_last_attached}:#{session_name}:#{session_windows}" |\
+    get_tmux_sessions "#{session_attached}:#{session_last_attached}:#{session_name}:#{session_windows}" |\
     sort -t: -k1,1n -k2,2nr |\
     while IFS=':' read -r is_attached last_attached session_name num_windows; do
         local attached_str=""
@@ -96,14 +98,14 @@ list() {
         printf "%-*s (session) (%s windows)%s\n" "$max_len" "$session_name" "$num_windows" "$attached_str"
     done
 
-    echo "$layouts" | awk -v max_len="$max_len" '{printf "%-*s (layout)\n", max_len, $1}'
+    echo "$layouts" | awk -v max_len="$max_len" '{printf "%-*s (layout)\n", max_len, $0}'
 
     if [ -n "$fragments" ]; then
-        echo "$fragments" | awk -v max_len="$max_len" '{printf "%-*s (fragment)\n", max_len, $1}'
+        echo "$fragments" | awk -v max_len="$max_len" '{printf "%-*s (fragment)\n", max_len, $0}'
     fi
 
     if [ -n "$dir_paths" ]; then
-        echo "$dir_paths" | awk -v max_len="$max_len" '{printf "%-*s (directory)\n", max_len, $1}'
+        echo "$dir_paths" | awk -v max_len="$max_len" '{printf "%-*s (directory)\n", max_len, $0}'
     fi
 }
 
@@ -113,8 +115,8 @@ preview() {
 
     case "$filter" in
         -s)
-            if get_tmux_sessions | grep -qx "$name"; then
-                run_tmux capture-pane -ep -t "$name"
+            if get_tmux_sessions "#{session_name}" | grep -qx "$name"; then
+                tmux capture-pane -ep -t "$name"
             else
                 echo "Error: session $name not found"
                 exit 1
@@ -153,18 +155,38 @@ preview() {
 }
 
 pick() {
-    local awk_cmd='awk "{gsub(\"[()]\", \"\", \$2); flag = substr(\$2, 1, 1); print \"tx preview -\" flag \" \" \$1}"'
-    local preview_cmd="echo {} | $awk_cmd | xargs -I{} bash -c {}"
+    local inner_awk='{
+        match($0, /\(([^)]+)\)/, arr);
+        type = substr(arr[1], 1, 1);
+        gsub(/\(.*\)/, "", $0);
+        name = $0
+        gsub(/[[:space:]]+$/, "", name)
+        printf "tx preview -%s \"%s\"", type, name
+    }'
+    local awk_cmd="awk '$inner_awk'"
+    local while_cmd='while read -r line; do echo \"$line\"; done'
+    local preview_cmd="echo {} | $awk_cmd | bash"
+
     local selected=$(picker "$(list)" "$preview_cmd")
 
     if [ -z "$selected" ]; then
         exit 1
     fi
 
-    read name type <<< $(
+    IFS=":" read name type <<< $(
         echo "$selected" |\
-        awk '{gsub("[()]", "", $2); flag = substr($2, 1, 1); print $1 " " flag}'
+        awk '{
+            match($0, /\(([^)]+)\)/, arr)
+            type = substr(arr[1], 1, 1)
+            gsub(/\(.*\)/, "", $0)
+            name = $0
+            gsub(/[[:space:]]+$/, "", name)
+            print name ":" type
+        }'
     )
+
+    echo "$name"
+    echo "$type"
 
     case "$type" in
         s)
@@ -213,8 +235,27 @@ sesh() {
         name="$RANDOM"
     done
 
-    run_tmux new-session -d -s "$name" -c "$dir"
+    tmux new-session -d -s "$name" -c "$dir"
     tmux_attach_or_switch "$name"
+}
+
+new_session() {
+    local name="$1"
+
+    if get_tmux_sessions "#{session_name}" | grep -qx "$name"; then
+        tmux_attach_or_switch "$name"
+        return 0
+    fi
+
+    if is_layout "$name"; then
+        . "$DATA_DIR/$name$LAYOUT_EXT"
+        return 0
+    fi
+
+    if is_fragment "$name"; then
+        echo "fragment $name"
+        return 0
+    fi
 }
 
 if [ $# -gt 0 ]; then
@@ -237,10 +278,15 @@ if [ $# -gt 0 ]; then
         sesh)
             sesh
             ;;
+        .)
+            tmux
+            ;;
+        *)
+            new_session "$1"
     esac
 else
     if [ -z "$TMUX" ]; then
-        run_tmux attach || { echo "Error: tmux is not running" ; exit 1; }
+        tmux attach 2>/dev/null || { echo "Error: tmux is not running" ; exit 1; }
     else
         echo "Error: already attached"
         exit 1
